### ISSUE TITLE
Uppdatera title och og-titel

### ISSUE THREAD

**Issue by Yonazarith** [Konkret-Media/wp-theme#26]
Formatet bör vara:
* ```Konkret``` för startsidan
* ```Konkret Info``` för kategorisidor
* ```Artikelns titel - Konkret Info``` för info-artiklar etc.

**Comment by supernaut** [comment]
Redan fixat i commit https://github.com/Konkret-Media/wp-theme/commit/8c3dd3a16c67e135f186864ef2b5701b303db498
